Update defender-for-devops.yml

diff --git a/.github/workflows/defender-for-devops.yml b/.github/workflows/defender-for-devops.yml
--- a/.github/workflows/defender-for-devops.yml
+++ b/.github/workflows/defender-for-devops.yml
@@ -1,21 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-#
-# Microsoft Security DevOps (MSDO) is a command line application which integrates static analysis tools into the development cycle.
-# MSDO installs, configures and runs the latest versions of static analysis tools
-# (including, but not limited to, SDL/security and compliance tools).
-#
-# The Microsoft Security DevOps action is currently in beta and runs on the windows-latest queue,
-# as well as Windows self hosted agents. ubuntu-latest support coming soon.
-#
-# For more information about the action , check out https://github.com/microsoft/security-devops-action
-#
-# Please note this workflow do not integrate your GitHub Org with Microsoft Defender For DevOps. You have to create an integration
-# and provide permission before this can report data back to azure.
-# Read the official documentation here : https://learn.microsoft.com/en-us/azure/defender-for-cloud/quickstart-onboard-github
-
 name: "Microsoft Defender For Devops"
 
 on:
@@ -28,7 +10,6 @@ on:
 
 jobs:
   MSDO:
-    # currently only windows latest is supported
     runs-on: windows-latest
 
     steps:
@@ -38,6 +19,13 @@ jobs:
         dotnet-version: |
           5.0.x
           6.0.x
+    - name: Install ESLint
+      run: |
+        npm install eslint@8.56.0 @microsoft/eslint-plugin-sdl@0.2.2 @microsoft/eslint-formatter-sarif@3.1.0 --global
+        if [ $? -ne 0 ]; then
+          echo "ESLint installation failed"
+          exit 1
+        fi
     - name: Run Microsoft Security DevOps
       uses: microsoft/security-devops-action@v1.6.0
       id: msdo
